/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteOffsRouteImport } from './routes/write-offs'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoriesRouteImport } from './routes/inventories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as InventoriesIndexRouteImport } from './routes/inventories.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as InventoriesIdRouteImport } from './routes/inventories.$id'
import { Route as ReportsExpectedIdRouteImport } from './routes/reports.expected.$id'

const WriteOffsRoute = WriteOffsRouteImport.update({
  id: '/write-offs',
  path: '/write-offs',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoriesRoute = InventoriesRouteImport.update({
  id: '/inventories',
  path: '/inventories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const InventoriesIndexRoute = InventoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoriesRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const InventoriesIdRoute = InventoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InventoriesRoute,
} as any)
const ReportsExpectedIdRoute = ReportsExpectedIdRouteImport.update({
  id: '/expected/$id',
  path: '/expected/$id',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inventories': typeof InventoriesRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/reports': typeof ReportsRouteWithChildren
  '/security': typeof SecurityRoute
  '/write-offs': typeof WriteOffsRoute
  '/inventories/$id': typeof InventoriesIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/inventories/': typeof InventoriesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/expected/$id': typeof ReportsExpectedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/security': typeof SecurityRoute
  '/write-offs': typeof WriteOffsRoute
  '/inventories/$id': typeof InventoriesIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/inventories': typeof InventoriesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reports/expected/$id': typeof ReportsExpectedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inventories': typeof InventoriesRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/reports': typeof ReportsRouteWithChildren
  '/security': typeof SecurityRoute
  '/write-offs': typeof WriteOffsRoute
  '/inventories/$id': typeof InventoriesIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/inventories/': typeof InventoriesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/expected/$id': typeof ReportsExpectedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/inventories'
    | '/login'
    | '/manager'
    | '/reports'
    | '/security'
    | '/write-offs'
    | '/inventories/$id'
    | '/reports/$id'
    | '/inventories/'
    | '/reports/'
    | '/reports/expected/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/manager'
    | '/security'
    | '/write-offs'
    | '/inventories/$id'
    | '/reports/$id'
    | '/inventories'
    | '/reports'
    | '/reports/expected/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/inventories'
    | '/login'
    | '/manager'
    | '/reports'
    | '/security'
    | '/write-offs'
    | '/inventories/$id'
    | '/reports/$id'
    | '/inventories/'
    | '/reports/'
    | '/reports/expected/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  InventoriesRoute: typeof InventoriesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  WriteOffsRoute: typeof WriteOffsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write-offs': {
      id: '/write-offs'
      path: '/write-offs'
      fullPath: '/write-offs'
      preLoaderRoute: typeof WriteOffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventories': {
      id: '/inventories'
      path: '/inventories'
      fullPath: '/inventories'
      preLoaderRoute: typeof InventoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/inventories/': {
      id: '/inventories/'
      path: '/'
      fullPath: '/inventories/'
      preLoaderRoute: typeof InventoriesIndexRouteImport
      parentRoute: typeof InventoriesRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/inventories/$id': {
      id: '/inventories/$id'
      path: '/$id'
      fullPath: '/inventories/$id'
      preLoaderRoute: typeof InventoriesIdRouteImport
      parentRoute: typeof InventoriesRoute
    }
    '/reports/expected/$id': {
      id: '/reports/expected/$id'
      path: '/expected/$id'
      fullPath: '/reports/expected/$id'
      preLoaderRoute: typeof ReportsExpectedIdRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface InventoriesRouteChildren {
  InventoriesIdRoute: typeof InventoriesIdRoute
  InventoriesIndexRoute: typeof InventoriesIndexRoute
}

const InventoriesRouteChildren: InventoriesRouteChildren = {
  InventoriesIdRoute: InventoriesIdRoute,
  InventoriesIndexRoute: InventoriesIndexRoute,
}

const InventoriesRouteWithChildren = InventoriesRoute._addFileChildren(
  InventoriesRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReportsExpectedIdRoute: typeof ReportsExpectedIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReportsExpectedIdRoute: ReportsExpectedIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  InventoriesRoute: InventoriesRouteWithChildren,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SecurityRoute: SecurityRoute,
  WriteOffsRoute: WriteOffsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
